import { Noto_Sans } from "next/font/google";
import { Toaster } from 'react-hot-toast';
import "./globals.css";

const notoSans = Noto_Sans({
  weight: ['400', '700'], 
  subsets: ['latin'], 
  variable: '--font-noto-sans', 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable} antialiased`}>
        <Toaster position="top-right" reverseOrder={false} /> 
        {children}
      </body>
    </html>
  );
}
